// <auto-generated />
using System;
using Assessment_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529172232_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assessment_Backend.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Assessment_Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiscountEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DiscountStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            Description = "A lightweight running shoe with a breathable Flyknit upper and flexible Free sole for natural movement.",
                            DiscountEndDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10.00m,
                            DiscountStartDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/ProductImages/domino-studio-164_6wVEHfI-unsplash.jpg",
                            Name = "Nike Free Flyknit",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Classic black sunglasses with polarized lenses, offering UV protection and timeless style.",
                            DiscountEndDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.00m,
                            DiscountStartDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/ProductImages/giorgio-trovato-K62u25Jk6vo-unsplash.jpg",
                            Name = "Ray-Ban Classic",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "A sleek chronograph watch with a stainless steel bracelet, dark green dial, and Roman numeral markers.",
                            DiscountEndDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 20.00m,
                            DiscountStartDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/ProductImages/pexels-javon-swaby-197616-2783873.jpg",
                            Name = "Michael Kors Chronograph Watch",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "A vibrant pink lipstick paired with a matching blush compact, ideal for a coordinated makeup look.",
                            DiscountEndDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10.00m,
                            DiscountStartDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/ProductImages/pexels-suzyhazelwood-2533266.jpg",
                            Name = "Pink Lipstick and Blush Set",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 16,
                            Description = "A compact mirrorless camera with a 16.3MP sensor, retro design, and a versatile 18-55mm f/2.8-4 lens for high-quality photography.",
                            DiscountEndDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.00m,
                            DiscountStartDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/ProductImages/pexels-madebymath-90946.jpg",
                            Name = "Fujifilm X-T10 with XF 18-55mm Lens",
                            Price = 800.00m
                        });
                });

            modelBuilder.Entity("Assessment_Backend.Models.Cart", b =>
                {
                    b.HasOne("Assessment_Backend.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Assessment_Backend.Models.Product", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
